#!/usr/bin/env node
// Emission: render a validated plan to a DocPage data module for
// DocumentationLayout (@wisent-ai/components >= 0.4.0) plus the nav
// structure. A pure function of the plan — no model, no probing. Claims are
// build-time verification metadata and are not rendered.
import { parseArgs } from "node:util";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { expandPath, readJson, printReport, isMain } from "./lib.mjs";

function renderSection(section) {
  const out = { title: section.title };
  for (const block of section.blocks) {
    switch (block.type) {
      case "paragraph":
        (out.paragraphs ??= []).push(block.text ?? "");
        break;
      case "bullets":
        (out.bullets ??= []).push(...(block.items ?? []));
        break;
      case "steps":
        (out.steps ??= []).push(...(block.items ?? []));
        break;
      case "code":
        (out.code ??= []).push(block.code ?? { code: "" });
        break;
      case "table":
        out.table = block.table;
        break;
      case "callout":
        out.callout = block.callout;
        break;
    }
  }
  return out;
}

/** Pure plan -> { docPages, docsNav, module } transform. */
export function emitPlan(plan) {
  // The support tail: support pages always come last, in plan order otherwise.
  const pages = [
    ...plan.pages.filter((p) => p.kind !== "support"),
    ...plan.pages.filter((p) => p.kind === "support"),
  ];
  const docPages = pages.map((p) => ({
    slug: p.slug,
    nav: p.nav,
    ...(p.group !== undefined ? { eyebrow: p.group } : {}),
    title: p.title,
    description: p.description,
    sections: p.sections.map(renderSection),
  }));

  const docsNav = [];
  const byLabel = new Map();
  for (const p of pages) {
    const label = p.group ?? "Documentation";
    if (!byLabel.has(label)) {
      const group = { label, items: [] };
      byLabel.set(label, group);
      docsNav.push(group);
    }
    byLabel.get(label).items.push({ slug: p.slug, label: p.nav });
  }

  const module =
    `// Generated by @wisent-ai/docs-cli from a validated docs plan` +
    ` (${plan.product} ${plan.version}).\n` +
    `// DocPage data module for DocumentationLayout (@wisent-ai/components >= 0.4.0).\n` +
    `// Every block in the source plan carries a verified claim. Do not edit by hand.\n\n` +
    `export const docPages = ${JSON.stringify(docPages, null, 2)} as const;\n\n` +
    `export const docsNav = ${JSON.stringify(docsNav, null, 2)} as const;\n`;

  return { docPages, docsNav, module };
}

async function main() {
  const { values } = parseArgs({
    options: { plan: { type: "string" }, out: { type: "string" } },
  });
  if (!values.plan || !values.out) {
    printReport({ error: "usage", detail: "node src/emit.mjs --plan plan.json --out <dir>" });
    process.exit(2);
  }
  const plan = readJson(values.plan);
  const outDir = expandPath(values.out);
  const { docPages, docsNav, module } = emitPlan(plan);
  mkdirSync(outDir, { recursive: true });
  const outFile = path.join(outDir, "docs.ts");
  writeFileSync(outFile, module);
  printReport({
    ok: true,
    out: outFile,
    pages: docPages.map((p) => p.slug),
    nav: docsNav.map((g) => ({ label: g.label, items: g.items.length })),
  });
}

if (isMain(import.meta.url)) await main();
